config/routes.rb
Rails.application.routes.draw do

  root to: 'visitors#index'

  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  resources :after_signup
  resources :deals

end

app/models/address.rb
class Address < ApplicationRecord

  POSTCODE_REGEXP = /[1-9]{1}[0-9]{3}[A-Z]{2}/
  COUNTRIES = %w(NL DE BE)

  before_validation do
    self.postcode = postcode.gsub(/\s/, '').upcase
  end

  belongs_to :user

  validates :name,
    presence: true

  validates :address,
    presence: true

  validates :postcode,
    presence: true,
    format: { with: POSTCODE_REGEXP }

  validates :city,
    presence: true

  validates :country,
    presence: true,
    inclusion: { in: COUNTRIES }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord

  BIC_REGEXP = /\A([a-zA-Z]){4}([a-zA-Z]){2}([0-9a-zA-Z]){2}([0-9a-zA-Z]{3})?\z/

  before_validation do
    self.iban = iban.gsub(/\s/, '').upcase
    self.bic  = bic.gsub(/\s/, '').upcase
  end

  belongs_to :user

  validates :name,
    presence: true

  validates :bank_name,
    presence: true

  validates :iban,
    presence: true,
    iban: true

  validates :bic,
    presence: true,
    format: { with: BIC_REGEXP }

  def pretty_iban
    IBANTools::IBAN.new(iban).prettify
  end

  def iban_country_code
    IBANTools::IBAN.new(iban).country_code
  end
end

app/models/concerns/default_record.rb
module DefaultRecord
  def default
    where(default: true).first
  end
end

app/models/deal.rb
class Deal < ApplicationRecord

  attr_accessor :party_b_email, :share, :request

  monetize :amount_cents,
    allow_nil: true,
    numericality: {
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: 100_000,
  }

  belongs_to :party_a, class_name: "User"
  belongs_to :party_b, class_name: "User"

  belongs_to :party_a_bank_account, class_name: "BankAccount", optional: true
  belongs_to :party_a_address,      class_name: "Address", optional: true
  belongs_to :party_b_bank_account, class_name: "BankAccount", optional: true
  belongs_to :party_b_address,      class_name: "Address", optional: true

  validates :title,
    presence: true

  scope :for_party_a, -> (id) { where(party_a_id: id) }
  scope :for_party_b, -> (id) { where(party_b_id: id) }

  scope :for_user, -> (user) { for_seller(user.id).or(for_buyer(user.id)) }

end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable

  has_many :addresses, -> { extending DefaultRecord },
    dependent: :destroy

  has_many :bank_accounts, -> { extending DefaultRecord },
    dependent: :destroy


  def deals
    Deal.for_user(self)
  end

end

app/controllers/after_signup_controller.rb
class AfterSignupController < ApplicationController
  include Wicked::Wizard
  steps :profile, :address, :bank_account

  before_action :authenticate_user!

  def show
    @user = current_user

    case step
    when :address then
      @address = Address.new
    when :bank_account then
      @bank_account = BankAccount.new
    end

    render_wizard
  end

  def update
    @user = current_user

    case step
    when :profile then
      @user.update_attributes(user_params)
    when :address then
      @address = @user.addresses.create(address_params)
    when :bank_account then
      @bank_account = @user.bank_accounts.create(bank_account_params)
    end

    render_wizard @user
  end

  private

  def user_params
    params.require(:user).permit(:full_name, :mobile_number, :whatsapp)
  end

  def address_params
    params.require(:address).permit(:name, :address, :postcode, :city, :country)
  end

  def bank_account_params
    params.require(:bank_account).permit(:name, :bank_name, :iban, :bic)
  end

  def finish_wizard_path
    deals_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :authenticate_user!

  def index
    @deals = current_user.deals
  end

  def new
    @deal = Deal.new
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  protected

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    after_signup_path(:profile)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
  end
end

app/helpers/after_signup_helper.rb
module AfterSignupHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/after_signup/address.html.haml
.container
  .row
    .col-sm-6.col-sm-offset-3
      %h1 Address

      = simple_form_for @address, url: wizard_path, method: :put do |f|
        = f.input :name
        = f.input :address
        = f.input :postcode
        = f.input :city
        = f.input :country, only: ["NL", "BE"], selected: "NL"

        = f.submit "Next"

app/views/after_signup/bank_account.html.haml
.container
  .row
    .col-sm-6.col-sm-offset-3
      %h1 Bank account

      = simple_form_for @bank_account, url: wizard_path, method: :put do |f|
        = f.input :name
        = f.input :bank_name
        = f.input :iban
        = f.input :bic

        = f.submit "Next"

app/views/after_signup/profile.html.haml
.container
  .row
    .col-sm-6.col-sm-offset-3
      %h1 Profile

      = simple_form_for @user, url: wizard_path, method: :put do |f|
        = f.input :full_name
        = f.input :mobile_number
        = f.input :whatsapp

        = f.submit "Next"

app/views/deals/index.html.haml
.container
  .row
    .col-sm-12
      - if @deals.any?

      - else
        .jumbotron
          %h1 You don't have any deals!
          %p Why not start now and create a new deal
          %p
            = link_to "Create a new deal", new_deal_path, class: 'btn btn-primary btn-lg', role: 'button'

app/views/deals/new.html.haml
.container
  = simple_form_for @deal do |f|
    .row
      .col-sm-6.col-sm-offset-3
        %h1 Create a new deal
        %p
          This form helps your create a new deals and handle all the administrative tasks for you.

    .row
      .col-sm-6.col-sm-offset-3
        %h2 The other party
        %p
          Please provide the email address of the other party. We'll use this address for notifications to the
          other party only. No spam.
        = f.input :party_b_email, as: :email

    .row
      .col-sm-6.col-sm-offset-3
        %h2 The deal

        %p
          Give some details, if necessary, about this deal to the other party. You must
          supply at least a title to identify this deal.

        = f.input :title
        = f.input :description

        = f.input :amount, wrapper: :vertical_input_group do
          %span.input-group-addon €
          = f.input_field :amount, class: 'form-control'

    .row
      .col-sm-3.col-sm-offset-3
        %h2 Share
        %p What do you want to share with the other party?

        = f.collection_check_boxes :share, [['address', 'Address'], ['bank_account', 'Bank account details']], :first, :last

      .col-sm-3
        %h2 Request
        %p What do you want to request from the other party?

        = f.collection_check_boxes :request, [['address', 'Address'], ['bank_account', 'Bank account details']], :first, :last

        

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default
  .container

    %button(type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-main-navbar-collapse-1" aria-expanded="false")
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand(href="#") Swappr

    .collapse.navbar-collapse#bs-main-navbar-collapse-1
      %ul.nav.navbar-nav
        %li
          %a(href="#") Link

      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          - # On thing
        - else
          %li.navbar-text You are not signed in.

app/views/layouts/application.html.haml
!!!
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")

    %title= content_for?(:title) ? yield(:title) : "Swappr.nl"

    = stylesheet_link_tag    "application"
    = javascript_include_tag "application", 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    = render 'layouts/navigation'
    = yield

app/views/visitors/index.html.haml
%h1 Welcome